[mgr]
show_hidden = true

[opener]
edit = [
    { run = 'nvim "%*"', block = true, desc = "Edit on NeoVim", for = "windows" }
]

vscode-ipynb = [
    { run = 'code -r "%*"', block = false, desc = "VS Code (ipynb)", for = "windows" },
]

[open]
prepend_rules = [
    # 1. Force ipynb to VS Code
    { url = "*.ipynb", use = "vscode-ipynb" },

    # 2. Force TOML and YAML specifically to NeoVim
    # This prevents the system's MIME-type association from picking VS Code
    { url = "*.{toml,yaml,yml}", use = "edit" },

    # 3. All other programming/text languages
    { url = "*.{txt,c,cpp,md,html,py,js,json,rs,go,pyw}", use = "edit" },

    # 4. Optional: Fallback to open EVERYTHING unrecognized in nvim
    # { url = "*", use = "edit" }
]